H/scrum 349
BerexiaDev/oclib pull request #100
Opened 2024-11-04 09:52 UTC by SoufianeAmghar

2024-11-06 13:57 UTC, Bouhm-Yassine requested changes

2024-11-06 13:57 UTC, Bouhm-Yassine commented on oc_lib/models/declaration_ana.py
> +    id = db.Column(db.Integer, primary_key=True)
why do you need type_pm  as it's always 'EP' ?!!

2024-11-06 16:19 UTC, SoufianeAmghar commented on oc_lib/models/declaration_ana.py
> +    id = db.Column(db.Integer, primary_key=True)
Fixed

2024-11-15 17:05 UTC, Bouhm-Yassine approved these changes

2024-11-23 15:54 UTC, Bouhm-Yassine approved these changes

2024-11-23 15:54 UTC, merged