Fix Pp statut logic
BerexiaDev/oclib pull request #73
Opened 2024-10-10 09:08 UTC by SoufianeAmghar

237

2024-10-10 21:56 UTC, Bouhm-Yassine requested changes

2024-10-10 21:56 UTC, Bouhm-Yassine commented on oc_lib/utils/events_decorator.py
add this check

![image](https://github.com/user-attachments/assets/abe9099e-c6a0-4c1f-98a3-fc5419dc229f)

2024-10-12 09:49 UTC, SoufianeAmghar commented on oc_lib/utils/events_decorator.py
Pushed and fixed

2024-10-12 16:27 UTC, Bouhm-Yassine approved these changes

2024-10-12 16:30 UTC, merged